package org.example.tgbot;

public enum DialogState {
    WAIT_RANDOM_OR_CERTAIN_TERM,
    WAIT_CONFIRMATION_TERM_INPUT,
    WAIT_DEFINITION,
    WAIT_CONFIRMATION_DEFINITION_INPUT,
    WAIT_TERM,
    DEFAULT,
}
